name: 🤖 AI Code Review

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run AI Bot Analysis
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node ai-bot.js

      - name: Commit and Push Report
        run: |
          git config --global user.name "jobdropo-ai-bot"
          git config --global user.email "bot@jobdropo.ai"
          git add ai-review-report.md
          git commit -m "🤖 Automated AI code review update" || echo "No changes to commit"
          git push
